/**
 * Keep Astryx inside the chat panel.
 *
 * Two stylesheets would otherwise reach the whole dashboard, and the fix for
 * both is the same one: pin their scope to the panel and exclude the document
 * root. Run this after `astryx theme build`; `npm run astryx:theme` does both.
 *
 * 1. THE RESET. `@astryxdesign/core/reset.css` is a preflight — it normalises
 *    `html`, `body` and every element on the page. The dashboard already ships
 *    Tailwind's preflight, so importing Astryx's on top would change Overview,
 *    Agents, API keys and Admin. It is rewritten here into
 *    `@scope ([data-astryx-theme]:not(:root))`, the attribute the Theme
 *    provider puts on its wrapper, so inside the panel Astryx gets exactly the
 *    reset it expects and outside it, nothing. This is Astryx's own mechanism:
 *    `astryx theme build` emits its prose reset the same way.
 *
 * 2. THE `:not(:root)`, which is the part that is easy to miss. Astryx's Theme
 *    decides it is the ROOT provider whenever no other Theme is above it, and a
 *    root provider copies `data-theme` and `data-astryx-theme` onto <html>. Ours
 *    is the only Theme in this app, so it always thinks it is the root — and the
 *    moment those attributes land on <html>, every `@scope ([data-astryx-theme…])`
 *    rule in the theme's own built CSS matches the whole document and the gothic
 *    prose styles start repainting the rest of the dashboard. Excluding `:root`
 *    from the scope root closes that door for good: the only element that can
 *    ever open an Astryx scope is the panel's own wrapper. The context that would
 *    let us tell Theme it is nested is private to the package, so this is the
 *    seam we have.
 *
 * Run: npm run astryx:scope   (or npm run astryx:theme to rebuild first)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import path from "node:path";

const require = createRequire(import.meta.url);
const themes = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "src", "themes");

// ---- 1. the reset ---------------------------------------------------------

const raw = readFileSync(require.resolve("@astryxdesign/core/reset.css"), "utf8");
const open = raw.indexOf("@layer reset {");
const body = raw.slice(open + "@layer reset {".length, raw.lastIndexOf("}"));

/** Selectors anchored on the document root can never match inside the scope. */
const ROOTED = /^\s*:where\((html|body)[^)]*\)/;

const kept = [];
let dropped = 0;
for (const block of body.split(/(?<=\})/)) {
  if (!block.includes("{")) continue;
  const rule = block.replace(/\/\*[\s\S]*?\*\//g, "").trim();
  if (rule.length === 0) continue;
  if (ROOTED.test(rule)) {
    dropped += 1;
    continue;
  }
  kept.push(rule.replace(/\n/g, "\n  "));
}

writeFileSync(
  path.join(themes, "astryx-reset.scoped.css"),
  `/*
 * @generated by scripts/scope-astryx.mjs — do not edit manually.
 * Source: @astryxdesign/core/reset.css
 *
 * Astryx's reset, scoped to the subtree the Theme provider owns so it cannot
 * touch the rest of the dashboard. ${dropped} rules anchored on html/body were
 * dropped because they can never match inside the scope; the panel gets its
 * color-scheme from Theme instead.
 */

@layer reset {
@scope ([data-astryx-theme]:not(:root)) {
  ${kept.join("\n\n  ")}
}
}
`,
);
console.log(`wrote src/themes/astryx-reset.scoped.css (${kept.length} rules, ${dropped} dropped)`);

// ---- 2. the built theme ---------------------------------------------------

const themeCss = path.join(themes, "gothic.css");
const before = readFileSync(themeCss, "utf8");
const after = before.replaceAll(
  /@scope \(\[data-astryx-theme="gothic"\]\)/g,
  '@scope ([data-astryx-theme="gothic"]:not(:root))',
);
if (after === before && !before.includes(':not(:root)')) {
  throw new Error("gothic.css has no @scope root to pin — did `astryx theme build` change shape?");
}
writeFileSync(themeCss, after);
console.log("pinned src/themes/gothic.css scopes off :root");
