/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/gothicTheme.ts
 * Command: astryx theme build src/themes/gothicTheme.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

import { gothicIconRegistry } from './icons';
/**
 * gothic theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { gothicTheme } from './gothic';
 *   import './gothic.css';
 */
export const gothicTheme = {
  name: 'gothic',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.75rem",
    "--font-size-base": "0.875rem",
    "--font-size-lg": "1.0625rem",
    "--font-size-xl": "1.25rem",
    "--font-size-2xl": "1.5rem",
    "--font-size-3xl": "1.8125rem",
    "--font-size-4xl": "2.1875rem",
    "--font-size-5xl": "2.625rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.3333",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.4",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.4118",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.4286",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.6667",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4286",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4118",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4286",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4286",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.6667",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2381",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2571",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.3793",
    "--duration-fast-min": "115ms",
    "--duration-fast": "150ms",
    "--duration-fast-max": "200ms",
    "--duration-medium-min": "265ms",
    "--duration-medium": "350ms",
    "--duration-medium-max": "465ms",
    "--duration-slow-min": "600ms",
    "--duration-slow": "800ms",
    "--duration-slow-max": "1065ms",
    "--font-family-body": "\"Geist Variable\", \"SF Pro Display\", \"Helvetica Neue\", system-ui, -apple-system, sans-serif",
    "--font-family-heading": "\"Geist Variable\", \"SF Pro Display\", \"Helvetica Neue\", system-ui, -apple-system, sans-serif",
    "--font-family-code": "\"Geist Mono Variable\", \"SF Mono\", \"JetBrains Mono\", ui-monospace, monospace",
    "--color-syntax-keyword": "#c39adb",
    "--color-syntax-string": "#a3c987",
    "--color-syntax-comment": "#6b7079",
    "--color-syntax-number": "#dec074",
    "--color-syntax-function": "#8aa1d8",
    "--color-syntax-type": "#c39adb",
    "--color-syntax-variable": "#E8F1F6",
    "--color-syntax-operator": "#96A0AB",
    "--color-syntax-constant": "#e6b85e",
    "--color-syntax-tag": "#d97580",
    "--color-syntax-attribute": "#dec074",
    "--color-syntax-property": "#7cc5b3",
    "--color-syntax-punctuation": "#7a8290",
    "--color-syntax-background": "#101314",
    "--color-accent": "light-dark(#24292D, #E8F1F6)",
    "--color-accent-muted": "light-dark(#24292D14, #E8F1F620)",
    "--color-neutral": "light-dark(#24292D14, #E8F1F61A)",
    "--color-background-surface": "light-dark(#ffffff, #1a1a19)",
    "--color-background-body": "light-dark(#f7f6f3, #0d0d0d)",
    "--color-overlay": "light-dark(#181c1fA6, #101314CC)",
    "--color-overlay-hover": "light-dark(#24292D0D, #E8F1F60D)",
    "--color-overlay-pressed": "light-dark(#24292D14, #E8F1F61A)",
    "--color-background-muted": "light-dark(#f1f0ec, #262624)",
    "--color-text-primary": "light-dark(#111111, #f5f5f2)",
    "--color-text-secondary": "light-dark(#6b6a66, #a3a29b)",
    "--color-text-disabled": "light-dark(#a8b1bb, #495056)",
    "--color-text-accent": "light-dark(#24292D, #E8F1F6)",
    "--color-on-dark": "#E8F1F6",
    "--color-on-light": "#101314",
    "--color-on-accent": "light-dark(#f3f6f8, #101314)",
    "--color-on-success": "#101314",
    "--color-on-error": "#101314",
    "--color-on-warning": "#101314",
    "--color-icon-accent": "light-dark(#24292D, #E8F1F6)",
    "--color-icon-primary": "light-dark(#111111, #f5f5f2)",
    "--color-icon-secondary": "light-dark(#6b6a66, #a3a29b)",
    "--color-icon-disabled": "light-dark(#a8b1bb, #495056)",
    "--color-background-card": "light-dark(#ffffff, #1a1a19)",
    "--color-background-popover": "light-dark(#ffffff, #262624)",
    "--color-background-inverted": "light-dark(#181c1f, #E8F1F6)",
    "--color-success": "#b3c79a",
    "--color-success-muted": "#b3c79a",
    "--color-error": "#c6a6a2",
    "--color-error-muted": "#c6a6a2",
    "--color-warning": "#d3c490",
    "--color-warning-muted": "#d3c490",
    "--color-border": "light-dark(#eaeaea, #2c2c2a)",
    "--color-border-emphasized": "light-dark(#d3d2cd, #494944)",
    "--color-skeleton": "light-dark(#dfe6eb, #495056)",
    "--color-shadow": "light-dark(#05365914, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--color-background-blue": "#a3b5d6",
    "--color-border-blue": "#8696b8",
    "--color-icon-blue": "#2a3b6e",
    "--color-text-blue": "#1f2c54",
    "--color-background-cyan": "#a3c2cf",
    "--color-border-cyan": "#86a4b1",
    "--color-icon-cyan": "#2a5e75",
    "--color-text-cyan": "#204858",
    "--color-background-gray": "light-dark(#dde4ea, #3d4248)",
    "--color-border-gray": "light-dark(#b7c0c8, #5d646b)",
    "--color-icon-gray": "light-dark(#24292D, #E8F1F6)",
    "--color-text-gray": "light-dark(#24292D, #E8F1F6)",
    "--color-background-green": "#b3c79a",
    "--color-border-green": "#96a880",
    "--color-icon-green": "#3a5e2c",
    "--color-text-green": "#244023",
    "--color-background-orange": "#d3b89a",
    "--color-border-orange": "#b6987d",
    "--color-icon-orange": "#8a4818",
    "--color-text-orange": "#6e3812",
    "--color-background-pink": "#c89aab",
    "--color-border-pink": "#aa7d8e",
    "--color-icon-pink": "#8d2d4c",
    "--color-text-pink": "#71223c",
    "--color-background-purple": "#b29bc4",
    "--color-border-purple": "#947da6",
    "--color-icon-purple": "#5a2370",
    "--color-text-purple": "#481b58",
    "--color-background-red": "#c6a6a2",
    "--color-border-red": "#a48581",
    "--color-icon-red": "#5e3a35",
    "--color-text-red": "#4a2520",
    "--color-background-teal": "#a3c2b6",
    "--color-border-teal": "#86a499",
    "--color-icon-teal": "#1f5e52",
    "--color-text-teal": "#174a40",
    "--color-background-yellow": "#d3c490",
    "--color-border-yellow": "#b6a775",
    "--color-icon-yellow": "#876515",
    "--color-text-yellow": "#6c5010",
    "--radius-none": "0px",
    "--radius-inner": "0.25rem",
    "--radius-element": "0.5rem",
    "--radius-container": "0.75rem",
    "--radius-page": "1rem",
    "--radius-chat": "0.5rem",
    "--radius-full": "9999px",
    "--shadow-low": "light-dark(0 1px 1px #05365914, 0 2px 6px #0536590F, 0 2px 4px #00000033, 0 4px 8px #00000040)",
    "--shadow-med": "light-dark(0 1px 2px #05365919, 0 2px 10px #05365914, 0 2px 4px #00000033, 0 4px 12px #00000040)",
    "--shadow-high": "light-dark(0 2px 3px #0536591F, 0 8px 20px #05365919, 0 4px 6px #00000040, 0 12px 24px #0000004D)",
    "--shadow-inset-hover": "light-dark(inset 0px 0px 0px 1px #5d646b26, inset 0px 0px 0px 1px #96A0AB30)",
    "--shadow-inset-selected": "light-dark(inset 0px 0px 0px 2px #5d646b40, inset 0px 0px 0px 2px #96A0AB50)",
    "--shadow-inset-success": "inset 0px 0px 0px 1px #87b06a50",
    "--shadow-inset-warning": "inset 0px 0px 0px 1px #d6b56a50",
    "--shadow-inset-error": "inset 0px 0px 0px 1px #d4485150"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "variant:secondary": {
        "backgroundColor": "var(--color-background-gray)",
        "color": "var(--color-text-gray)",
        "borderColor": "transparent",
        "borderWidth": "0"
      },
      "variant:ghost": {
        ":hover": {
          "backgroundColor": "var(--color-overlay-hover)"
        }
      },
      "variant:destructive": {
        "backgroundColor": "var(--color-error)",
        "color": "var(--color-text-red)"
      }
    },
    "badge": {
      "base": {
        "borderRadius": "var(--radius-element)",
        "fontWeight": "var(--font-weight-medium)"
      },
      "variant:info": {
        "backgroundColor": "var(--color-background-blue)",
        "color": "var(--color-text-blue)"
      },
      "variant:neutral": {
        "backgroundColor": "var(--color-background-gray)",
        "color": "var(--color-text-gray)"
      },
      "variant:success": {
        "backgroundColor": "var(--color-background-green)",
        "color": "var(--color-text-green)"
      },
      "variant:warning": {
        "backgroundColor": "var(--color-background-yellow)",
        "color": "var(--color-text-yellow)"
      },
      "variant:error": {
        "backgroundColor": "var(--color-background-red)",
        "color": "var(--color-text-red)"
      }
    },
    "banner": {
      "base": {
        "borderRadius": "var(--radius-element)"
      },
      "status:info": {
        "backgroundColor": "var(--color-background-blue)",
        "--color-text-primary": "var(--color-text-blue)",
        "--color-text-secondary": "var(--color-text-blue)",
        "--color-accent": "var(--color-text-blue)"
      },
      "status:success": {
        "backgroundColor": "var(--color-background-green)",
        "--color-text-primary": "var(--color-text-green)",
        "--color-text-secondary": "var(--color-text-green)",
        "--color-success": "var(--color-text-green)"
      },
      "status:warning": {
        "backgroundColor": "var(--color-background-yellow)",
        "--color-text-primary": "var(--color-text-yellow)",
        "--color-text-secondary": "var(--color-text-yellow)",
        "--color-warning": "var(--color-text-yellow)"
      },
      "status:error": {
        "backgroundColor": "var(--color-background-red)",
        "--color-text-primary": "var(--color-text-red)",
        "--color-text-secondary": "var(--color-text-red)",
        "--color-error": "var(--color-text-red)"
      }
    },
    "card": {
      "base": {
        "padding": "var(--spacing-3)",
        "borderRadius": "var(--radius-container)"
      },
      "variant:blue": {
        "--color-text-primary": "var(--color-text-blue)",
        "--color-text-secondary": "var(--color-text-blue)"
      },
      "variant:cyan": {
        "--color-text-primary": "var(--color-text-cyan)",
        "--color-text-secondary": "var(--color-text-cyan)"
      },
      "variant:gray": {
        "--color-text-primary": "var(--color-text-gray)",
        "--color-text-secondary": "var(--color-text-gray)"
      },
      "variant:green": {
        "--color-text-primary": "var(--color-text-green)",
        "--color-text-secondary": "var(--color-text-green)"
      },
      "variant:orange": {
        "--color-text-primary": "var(--color-text-orange)",
        "--color-text-secondary": "var(--color-text-orange)"
      },
      "variant:pink": {
        "--color-text-primary": "var(--color-text-pink)",
        "--color-text-secondary": "var(--color-text-pink)"
      },
      "variant:purple": {
        "--color-text-primary": "var(--color-text-purple)",
        "--color-text-secondary": "var(--color-text-purple)"
      },
      "variant:red": {
        "--color-text-primary": "var(--color-text-red)",
        "--color-text-secondary": "var(--color-text-red)"
      },
      "variant:teal": {
        "--color-text-primary": "var(--color-text-teal)",
        "--color-text-secondary": "var(--color-text-teal)"
      },
      "variant:yellow": {
        "--color-text-primary": "var(--color-text-yellow)",
        "--color-text-secondary": "var(--color-text-yellow)"
      }
    },
    "section": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "field": {
      "base": {
        "borderRadius": "var(--radius-element)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  icons: gothicIconRegistry,
};

export { gothicIconRegistry };
