/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/gothicTheme.ts
 * Command: astryx theme build src/themes/gothicTheme.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const gothicIconRegistry: IconRegistry;
export declare const gothicTheme: DefinedTheme;
